title: "Relate"
description: "Blazingly fast database access layer for Scala."
baseurl: /relate

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude: [
  Gemfile*,
  .gitignore,
  README.md
]
